//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GBUZhilishnikKuncevo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Accounting
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Accounting()
        {
            this.ServiceCheck = new HashSet<ServiceCheck>();
        }
    
        public int id { get; set; }
        public Nullable<int> counterId { get; set; }
        public double counterReading { get; set; }
        public System.DateTime accountingStart { get; set; }
        public System.DateTime accountingEnd { get; set; }
        public int serviceId { get; set; }
        public Nullable<int> bankBookId { get; set; }
    
        public virtual BankBook BankBook { get; set; }
        public virtual Counter Counter { get; set; }
        public virtual Service Service { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServiceCheck> ServiceCheck { get; set; }
    }
}
