//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GBUZhilishnikKuncevo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Address
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Address()
        {
            this.Apartment = new HashSet<Apartment>();
        }
    
        public int id { get; set; }
        public string city { get; set; }
        public string area { get; set; }
        public string street { get; set; }
        public string buildingNumber { get; set; }
        public string buildingCorpse { get; set; }
        public int entranceNumber { get; set; }
        public int floorNumber { get; set; }
        public int apartmentNumber { get; set; }
        public string fullAddress => $"{city} {area} {street} {buildingNumber} {buildingCorpse} {entranceNumber} {floorNumber} {apartmentNumber}";

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Apartment> Apartment { get; set; }
    }
}
