//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GBUZhilishnikKuncevo.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class menshakova_publicUtilitiesEntities : DbContext
    {
        public menshakova_publicUtilitiesEntities()
            : base("name=menshakova_publicUtilitiesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Accounting> Accounting { get; set; }
        public virtual DbSet<Address> Address { get; set; }
        public virtual DbSet<Apartment> Apartment { get; set; }
        public virtual DbSet<BankBook> BankBook { get; set; }
        public virtual DbSet<Benefit> Benefit { get; set; }
        public virtual DbSet<Client> Client { get; set; }
        public virtual DbSet<Counter> Counter { get; set; }
        public virtual DbSet<Gender> Gender { get; set; }
        public virtual DbSet<Ownership> Ownership { get; set; }
        public virtual DbSet<Passport> Passport { get; set; }
        public virtual DbSet<PaymentState> PaymentState { get; set; }
        public virtual DbSet<Proprietary> Proprietary { get; set; }
        public virtual DbSet<Service> Service { get; set; }
        public virtual DbSet<ServiceCheck> ServiceCheck { get; set; }
        public virtual DbSet<SNILS> SNILS { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TIN> TIN { get; set; }
        public virtual DbSet<TotalCheck> TotalCheck { get; set; }
        public virtual DbSet<TypeOfCounter> TypeOfCounter { get; set; }
        public virtual DbSet<TypeOfService> TypeOfService { get; set; }
    }
}
