//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GBUZhilishnikKuncevo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceCheck
    {
        public int id { get; set; }
        public int accountingId { get; set; }
        public Nullable<decimal> totalPayble { get; set; }
        public string description { get; set; }
    
        public virtual Accounting Accounting { get; set; }
    }
}
